channels:
- conda-forge
- bioconda
dependencies:
- r-base
- r-essentials
- r-factominer
- r-factoextra




#- conda install -c bioconda r-factominer
#- conda install -c conda-forge r-factoextra
#conda install r-factominer
#conda install -c bioconda sra-tools=2.7.0
